site_name: Material Roblox
site_url: https://shunnedreality.github.io/material-roblox
repo_name: shunnedreality/material-roblox
repo_url: https://github.com/shunnedreality/material-roblox
theme:
  icon:
    admonition:
      note: octicons/tag-16
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.top
    - navigation.indexes
nav:
  - Home: index.md
  - Quickstart: Quickstart.md
  - Components:
      - Components/Dialog.md
      - Components/Icon.md
      - Components/NavigationBar.md
      - Components/NavigationTab.md
      - Components/Ripple.md
      - Components/Tabs.md
      - Components/TabItem.md
      - Components/TextButton.md
      - Components/Banner.md
  - Utils:
      - Utils/MaterialColorUtilities.md
      - Utils/MaterialTypography.md
      - Utils/ProvideMaterial.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences