[package]
name = "shunnedreality/materialroblox"
description = "Material Design 3 components that actually match Google specs"
version = "0.9.1"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"

[dependencies]
Fusion = "elttob/fusion@~0.3.0"
luau-polyfill = "core-packages/luau-polyfill@1.2.3"
promise = "evaera/promise@4.0.0"
luau-regexp = "jsdotlua/luau-regexp@0.2.1"