[package]
name = "shunnedreality/material-roblox"
description = "Material Design 3 components that actually match Google specs"
version = "0.0.8"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"

[dependencies]
Fusion = "elttob/fusion@~0.3.0"