local Dialog = require("@self/Dialog");
local Icon = require("@self/Icon");
local NavigationTab = require("@self/NavigationTab");
local NavigationBar = require("@self/NavigationBar");
local Ripple = require("@self/Ripple");
local TabItem = require("@self/TabItem");
local Tabs = require("@self/Tabs");
local TextButton = require("@self/TextButton");
local Banner = require("@self/Banner");
local Switch = require("@self/Switch");
local SideSheet = require("@self/SideSheet");
local IconButton = require("@self/IconButton");
local Menu = require("@self/Menu");
local Item = require("@self/Item");
local Shadow = require("@self/Shadow");

return {
    Dialog = Dialog,
    Icon = Icon,
    NavigationTab = NavigationTab,
    NavigationBar = NavigationBar,
    Ripple = Ripple,
    TabItem = TabItem,
    Tabs = Tabs,
    TextButton = TextButton,
    Banner = Banner,
    Switch = Switch,
    SideSheet = SideSheet,
    IconButton = IconButton,
    Menu = Menu,
    Item = Item,
    Shadow = Shadow
}