local Dialog = require("@self/Dialog");
local Icon = require("@self/Icon");
local NavigationTab = require("@self/NavigationTab");
local NavigationBar = require("@self/NavigationBar");
local Ripple = require("@self/Ripple");
local TabItem = require("@self/TabItem");
local Tabs = require("@self/Tabs");
local TextButton = require("@self/TextButton");
local Banner = require("@self/Banner");
local Switch = require("@self/Switch")

return {
    Dialog = Dialog,
    Icon = Icon,
    NavigationTab = NavigationTab,
    NavigationBar = NavigationBar,
    Ripple = Ripple,
    TabItem = TabItem,
    Tabs = Tabs,
    TextButton = TextButton,
    Banner = Banner,
    Switch = Switch
}