local Dialog = require("@self/Dialog");
local Icon = require("@self/Icon");
local NavigationTab = require("@self/NavigationTab");
local NavigationBar = require("@self/NavigationBar");
local Ripple = require("@self/Ripple");
local TabItem = require("@self/TabItem");
local Tabs = require("@self/Tabs");

return {
    Dialog = Dialog,
    Icon = Icon,
    NavigationTab = NavigationTab,
    NavigationBar = NavigationBar,
    Ripple = Ripple,
    TabItem = TabItem,
    Tabs = Tabs
}